
package org.corporateforce.server.webservices.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13
 * Sun Dec 28 17:51:58 BRT 2014
 * Generated source version: 2.7.13
 */

@XmlRootElement(name = "changePasswordSecureUsers", namespace = "http://webservices.server.corporateforce.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "changePasswordSecureUsers", namespace = "http://webservices.server.corporateforce.org/", propOrder = {"id", "oldpassword", "newpassword"})

public class ChangePasswordSecureUsers {

    @XmlElement(name = "id")
    private java.lang.Integer id;
    @XmlElement(name = "oldpassword")
    private java.lang.String oldpassword;
    @XmlElement(name = "newpassword")
    private java.lang.String newpassword;

    public java.lang.Integer getId() {
        return this.id;
    }

    public void setId(java.lang.Integer newId)  {
        this.id = newId;
    }

    public java.lang.String getOldpassword() {
        return this.oldpassword;
    }

    public void setOldpassword(java.lang.String newOldpassword)  {
        this.oldpassword = newOldpassword;
    }

    public java.lang.String getNewpassword() {
        return this.newpassword;
    }

    public void setNewpassword(java.lang.String newNewpassword)  {
        this.newpassword = newNewpassword;
    }

}

