
package org.corporateforce.server.webservices.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13
 * Sun Dec 28 17:51:58 BRT 2014
 * Generated source version: 2.7.13
 */

@XmlRootElement(name = "changeManagerUsers", namespace = "http://webservices.server.corporateforce.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "changeManagerUsers", namespace = "http://webservices.server.corporateforce.org/", propOrder = {"id", "manager"})

public class ChangeManagerUsers {

    @XmlElement(name = "id")
    private int id;
    @XmlElement(name = "manager")
    private int manager;

    public int getId() {
        return this.id;
    }

    public void setId(int newId)  {
        this.id = newId;
    }

    public int getManager() {
        return this.manager;
    }

    public void setManager(int newManager)  {
        this.manager = newManager;
    }

}

