
package org.corporateforce.server.webservices.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13
 * Sun Dec 28 17:51:58 BRT 2014
 * Generated source version: 2.7.13
 */

@XmlRootElement(name = "createSimpleUsers", namespace = "http://webservices.server.corporateforce.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createSimpleUsers", namespace = "http://webservices.server.corporateforce.org/", propOrder = {"profile", "office", "role", "manager", "username", "password"})

public class CreateSimpleUsers {

    @XmlElement(name = "profile")
    private int profile;
    @XmlElement(name = "office")
    private int office;
    @XmlElement(name = "role")
    private int role;
    @XmlElement(name = "manager")
    private int manager;
    @XmlElement(name = "username")
    private java.lang.String username;
    @XmlElement(name = "password")
    private java.lang.String password;

    public int getProfile() {
        return this.profile;
    }

    public void setProfile(int newProfile)  {
        this.profile = newProfile;
    }

    public int getOffice() {
        return this.office;
    }

    public void setOffice(int newOffice)  {
        this.office = newOffice;
    }

    public int getRole() {
        return this.role;
    }

    public void setRole(int newRole)  {
        this.role = newRole;
    }

    public int getManager() {
        return this.manager;
    }

    public void setManager(int newManager)  {
        this.manager = newManager;
    }

    public java.lang.String getUsername() {
        return this.username;
    }

    public void setUsername(java.lang.String newUsername)  {
        this.username = newUsername;
    }

    public java.lang.String getPassword() {
        return this.password;
    }

    public void setPassword(java.lang.String newPassword)  {
        this.password = newPassword;
    }

}

