
package org.corporateforce.server.webservices.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13
 * Sun Dec 28 17:51:58 BRT 2014
 * Generated source version: 2.7.13
 */

@XmlRootElement(name = "createWithContactsUsers", namespace = "http://webservices.server.corporateforce.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createWithContactsUsers", namespace = "http://webservices.server.corporateforce.org/", propOrder = {"profile", "office", "role", "manager", "username", "password", "firstname", "lastname", "gender", "date"})

public class CreateWithContactsUsers {

    @XmlElement(name = "profile")
    private int profile;
    @XmlElement(name = "office")
    private int office;
    @XmlElement(name = "role")
    private int role;
    @XmlElement(name = "manager")
    private int manager;
    @XmlElement(name = "username")
    private java.lang.String username;
    @XmlElement(name = "password")
    private java.lang.String password;
    @XmlElement(name = "firstname")
    private java.lang.String firstname;
    @XmlElement(name = "lastname")
    private java.lang.String lastname;
    @XmlElement(name = "gender")
    private int gender;
    @XmlElement(name = "date")
    private java.util.Date date;

    public int getProfile() {
        return this.profile;
    }

    public void setProfile(int newProfile)  {
        this.profile = newProfile;
    }

    public int getOffice() {
        return this.office;
    }

    public void setOffice(int newOffice)  {
        this.office = newOffice;
    }

    public int getRole() {
        return this.role;
    }

    public void setRole(int newRole)  {
        this.role = newRole;
    }

    public int getManager() {
        return this.manager;
    }

    public void setManager(int newManager)  {
        this.manager = newManager;
    }

    public java.lang.String getUsername() {
        return this.username;
    }

    public void setUsername(java.lang.String newUsername)  {
        this.username = newUsername;
    }

    public java.lang.String getPassword() {
        return this.password;
    }

    public void setPassword(java.lang.String newPassword)  {
        this.password = newPassword;
    }

    public java.lang.String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(java.lang.String newFirstname)  {
        this.firstname = newFirstname;
    }

    public java.lang.String getLastname() {
        return this.lastname;
    }

    public void setLastname(java.lang.String newLastname)  {
        this.lastname = newLastname;
    }

    public int getGender() {
        return this.gender;
    }

    public void setGender(int newGender)  {
        this.gender = newGender;
    }

    public java.util.Date getDate() {
        return this.date;
    }

    public void setDate(java.util.Date newDate)  {
        this.date = newDate;
    }

}

