
package org.corporateforce.server.webservices.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13
 * Sun Dec 28 17:51:58 BRT 2014
 * Generated source version: 2.7.13
 */

@XmlRootElement(name = "loginUsers", namespace = "http://webservices.server.corporateforce.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "loginUsers", namespace = "http://webservices.server.corporateforce.org/", propOrder = {"username", "password"})

public class LoginUsers {

    @XmlElement(name = "username")
    private java.lang.String username;
    @XmlElement(name = "password")
    private java.lang.String password;

    public java.lang.String getUsername() {
        return this.username;
    }

    public void setUsername(java.lang.String newUsername)  {
        this.username = newUsername;
    }

    public java.lang.String getPassword() {
        return this.password;
    }

    public void setPassword(java.lang.String newPassword)  {
        this.password = newPassword;
    }

}

